---
- name: Criando um projeto no GITLAB
  hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Create GitLab Project in group Ansible
    community.general.gitlab_project:
      api_url: http://gitlab.example.com/
      validate_certs: False
      api_token: "{{ access_token }}"
      name: criado_via_Tower_AWX
      group: automacao
      visibility: internal
      issues_enabled: False
      merge_method: rebase_merge
      wiki_enabled: True
      snippets_enabled: True
      #import_url: http://git.example.com/example/lab.git
      state: present
    delegate_to: localhost

  - name: "Adding a project hook"
    community.general.gitlab_hook:
      api_url: https://gitlab.example.com/
      api_token: "{{ access_token }}"
      validate_certs: False
      project: "automacao/criado_via_Tower_AWX"
      hook_url: "https://my-ci-server.example.com/gitlab-hook"
      state: present
      push_events: yes
      tag_push_events: yes
      merge_requests_events: yes
      hook_validate_certs: no
      token: "my-super-secret-token-that-my-ci-server-will-check"    