---
- name: Criando um projeto no GITLAB
  hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Create GitLab Project in group Ansible
    community.general.gitlab_project:
      api_url: http://gitlab.example.com/
      validate_certs: False
      api_token: "{{ access_token }}"
      name: criado_via_Tower_AWX
      group: automacao
      visibility: internal
      issues_enabled: False
      merge_method: rebase_merge
      wiki_enabled: True
      snippets_enabled: True
      #import_url: http://git.example.com/example/lab.git
      state: present
    delegate_to: localhost