---
- name: Post configuration CentOS8 on GCP
  hosts: all
  become: true
  vars:
    package: cockpit
  tasks:
    - name: Instalando pacotes adicionais
      dnf:
        name: "{{package}}"
        state: latest

    - name: Habilitando serviços
      ansible.builtin.service:
        name: "{{package}}"
        state: started
        enabled: yes

    - name: Restart servers
      reboot:
        reboot_timeout: 120