---
- name: Stress test on kubernetes service
  hosts: all
  tasks:
  - name: Pause play until a URL is reachable from this host
    uri:
      url: "http://20.75.2.25"
      follow_redirects: none
      method: GET
    register: _result
    until: _result.status == 404
    retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
    delay: 1 # Every 5 seconds